import uniqid from "uniqid";

const projects = [
  {
    _id: uniqid(),
    mobile: true,
    name: "Socially - PWA",
    technologies: [
      "React",
      "Redux",
      "Rest API",
      "React Router",
      "Material UI",
      "Styled Components",
    ],
    site: "https://curious-sable-29bfe2.netlify.app/",
    github: "https://github.com/rartamosa/Socially-PWA",
    image: "./assets/socially.png",
  },
  {
    _id: uniqid(),
    mobile: false,
    name: "To Do App (extended)",
    technologies: [
      "React",
      "React Router",
      "Rest API",
      "Custom Hook",
      "custom reusable component",
      "NPM reusable components",
    ],
    site: "https://bejewelled-cat-b72838.netlify.app",
    github: "https://github.com/rartamosa/To-do-app-extended",
    image: "./assets/to-do-app-extended.png",
  },
  {
    _id: uniqid(),
    mobile: false,
    name: "to do app",
    technologies: [
      "local storage",
      "React",
      "custom hook",
      "NPM reusable component",
    ],
    site: "https://reliable-dango-25e722.netlify.app",
    github: "https://github.com/rartamosa/To-do-app",
    image: "./assets/to-do-app.png",
  },
  {
    _id: uniqid(),
    mobile: false,
    name: "adopt a dog",
    technologies: [
      "HTML",
      "CSS",
      "CSS variables",
      "fetch()",
      "vanilla JavaScript",
      "Rest API",
      "group project",
    ],
    site: "https://astounding-choux-236d52.netlify.app/",
    github: "https://github.com/rartamosa/Adopt-a-Dog-Project",
    image: "./assets/adopt-a-dog.png",
  },
  {
    _id: uniqid(),
    mobile: false,
    name: "happy thoughts - asynchronous JS app",
    technologies: ["HTML", "CSS", "fetch()", "vanilla JavaScript", "Rest API"],
    site: "https://dazzling-chimera-2c716e.netlify.app/",
    github: "https://github.com/rartamosa/Happy-Thoughts-asynchronous-js-app",
    image: "./assets/happy-thoughts.png",
  },
  {
    _id: uniqid(),
    mobile: false,
    name: "calculator app",
    technologies: ["HTML", "CSS", "vanilla JavaScript"],
    site: "https://peaceful-sprinkles-9d3679.netlify.app/",
    github: "https://github.com/rartamosa/calculator-app",
    image: "./assets/calculator-app.png",
  },
];

export default projects;
